[package]
name = "malina"
version = "0.1.0"
authors = ["Michał Budziak <michal.mariusz.b@gmail.com>"]
edition = "2018"

[dependencies]
#blurz = "0.4.0"
dbus = "0.9.0"
dbus-crossroads = "0.3.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
